# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{g_named_scope_filters}
  s.version = "1.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["C. Jason Harrelson (midas)"]
  s.date = %q{2010-07-19}
  s.description = %q{A UI component that generates an unordered list of filters that use named scopes within an ActiveRecord model to filter a list.  It is not tied to a table or list specifically as it simply manipulates the url, resulting  in a manipulation of any collection (list, table, etc.) it may be coupled with.}
  s.email = %q{jason@lookforwardenterprises.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "g_named_scope_filters.gemspec",
     "lib/g_named_scope_filters.rb",
     "lib/g_named_scope_filters/view_helpers.rb",
     "script/console",
     "script/destroy",
     "script/generate",
     "spec/g_named_scope_filters_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/midas/g_named_scope_filters}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A UI component that generates an unordered list of filters that use named scopes within an ActiveRecord model to filter a list.}
  s.test_files = [
    "spec/g_named_scope_filters_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.8"])
      s.add_runtime_dependency(%q<rails>, [">= 2.2.0"])
      s.add_runtime_dependency(%q<guilded>, [">= 1.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.8"])
      s.add_dependency(%q<rails>, [">= 2.2.0"])
      s.add_dependency(%q<guilded>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.8"])
    s.add_dependency(%q<rails>, [">= 2.2.0"])
    s.add_dependency(%q<guilded>, [">= 1.0.0"])
  end
end

